# Generated by Django 2.2.6 on 2019-10-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='STATUS',
            field=models.CharField(default='You Can Apply for LOAN', max_length=100),
        ),
    ]
