# Generated by Django 2.2.6 on 2019-10-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='STATUS',
            field=models.CharField(default='YOU CAN AVAIL THE PERSONAL LOAN', max_length=100),
        ),
    ]
