# Generated by Django 2.2.6 on 2019-10-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_auto_20191027_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loandetail',
            old_name='profile',
            new_name='user',
        ),
    ]
