# Generated by Django 2.2.6 on 2019-10-29 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_auto_20191027_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetail',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(30)]),
        ),
    ]
